routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// CRUD for gallery
Route::resource('gallery', 'GalleryController');

// the index of the website is the gallery
Route::get('/', function () { return redirect('/gallery'); });

// about and contact
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'HomeController@contact')->name('contact');

// route needed for comments
Route::put('/comment/{gallery}', 'CommentaireController@store')->name('comment.store');
Route::get('/comment/{comment}', "CommentaireController@edit")->name('comment.edit');
Route::put('/comment/{comment}/edit', 'CommentaireController@update')->name('comment.update');
Route::delete('/comment/{comment}', "CommentaireController@destroy")->name('comment.destroy');

// Authentication
Auth::routes();

// route to profile
Route::get('/profil', 'HomeController@profil')->name('profil')->middleware('auth');

// route to get games corresponding to tag;
Route::get('/tag/{tag}', 'GalleryController@tag')->name('tagged');

resources/views/logged.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{{ route('gallery.index') }}">Ludothèque</a>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
            <li class="nav-item"><a href="{{ route('about') }}" class="nav-link">À propos</a></li>
            <li class="nav-item"><a href="{{ route('contact') }}" class="nav-link">Nous contacter</a></li>
        </ul>


    </div>

    <!-- Right Side Of Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Authentication Links -->
        @guest
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">{{ __('navbar.Login') }}</a>
            </li>
            @if (Route::has('register'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">{{ __('navbar.Register') }}</a>
                </li>
            @endif
        @else
            <a class="nav-link" href="{{ route('logout') }}"
               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                {{ __('navbar.Logout') }}
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        @endguest
    </ul>
</nav>