routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// CRUD for gallery
Route::resource('gallery', 'GalleryController');

// the index of the website is the gallery
Route::get('/', function () { return redirect('/gallery'); });

// about and contact
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'HomeController@contact')->name('contact');

// route needed for comments
Route::put('/comment/{gallery}', 'CommentaireController@store')->name('comment.store');
Route::get('/comment/{comment}', "CommentaireController@edit")->name('comment.edit');
Route::put('/comment/{comment}/edit', 'CommentaireController@update')->name('comment.update');
Route::delete('/comment/{comment}', "CommentaireController@destroy")->name('comment.destroy');

// Authentication
Auth::routes();

// route to profile
Route::get('/profil', 'HomeController@profil')->name('profil')->middleware('auth');

// route to get games corresponding to tag;
Route::get('/tag/{tag}', 'GalleryController@tag')->name('tagged');

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Games;
use App\Models\Tag;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $games = Games::all();
        $tags = Tag::all();
        return view('gallery.index', compact('games', 'tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::all();
        return view('gallery.create', compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $validated = $this->validate($request, [
            'file' => 'required|image',
            'nom' => 'required',
            'annee_sortie' => 'required|integer',
            'age_min' => 'required|integer',
            'min_joueur' => 'required|integer',
            'max_joueur' => 'required|integer',
            'min_duree' => 'required|integer',
            'max_duree' => 'required|integer',
            'description' => 'required',
            'tags' => 'nullable|array'
        ]);

        $game = new Games($validated);

        // get filename
        $filename = $request->file->getClientOriginalName();
        // move it to the upload directory
        $request->file->move('upload', $filename);

        $game->thumbnail = "/upload/$filename";

        $game->save();

        $this->saveTag($game, $validated);

        session()->flash('success', "Ce jeu a bien été créée.");

        return redirect('/gallery');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        /** @var Games $game */
        $game = is_numeric($id) ? Games::find($id) : null;
        if (!is_null($game)) {
            $tags = $game->tag()->get();
            $comments = $game->comments()->get();
            return view('gallery.show', compact('game', 'tags', 'comments'));
        }
        session()->flash('error', "Ce jeu n'existe pas.");
        return redirect('/gallery');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $game = is_numeric($id) ? Games::find($id) : null;
        $tags = Tag::all();
        if (!is_null($game)) {
            $gametags = $game->tag()->get()->map->id->toArray();
            return view('gallery.edit', compact("game", "tags", "gametags"));
        }
        session()->flash('error', "Ce jeu n'existe pas.");
        return redirect('/gallery');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        /** @var Games $game */
        $game = is_numeric($id) ? Games::find($id) : null;

        if (!is_null($game)) {
            $validated = $this->validate($request, [
                'thumbnail' => 'required|url',
                'nom' => 'required',
                'annee_sortie' => 'required|integer',
                'age_min' => 'required|integer',
                'min_joueur' => 'required|integer',
                'max_joueur' => 'required|integer',
                'min_duree' => 'required|integer',
                'max_duree' => 'required|integer',
                'description' => 'required',
                'tags' => 'nullable|array'
            ]);

            $game->update($validated);
            $game->save();

            $this->saveTag($game, $validated);

            session()->flash('success', "Ce jeu a bien été modifié.");

            return redirect("/gallery/$id");
        }
        session()->flash('error', "Ce jeu n'existe pas.");
        return redirect('/gallery');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy($id)
    {
        /** @var Games $game */
        $game = is_numeric($id) ? Games::find($id) : null;
        if (!is_null($game)) {
            $game->delete();
            session()->flash('success', "Le jeu a bien été supprimé.");
        } else {
            session()->flash('error', "Ce jeu n'existe pas.");
        }
        return redirect('/gallery');
    }

    public function tag($id) {

        $tag = is_numeric($id) ? Tag::find($id) : null;
        if (!is_null($tag)) {

            $games = $tag->games()->get();
            $tags = Tag::all();

            return view('gallery.tagged', compact('games', 'tag', 'tags'));
        }
        session()->flash('error', "Ce tag n'existe pas");
        return redirect('/gallery');
    }

    private function saveTag(Games $game, array $validated)
    {
        if (array_key_exists('tags', $validated) && !empty($validated['tags'])) {
            /** @var Model $game */
            $tags = Tag::all()->map->id->toArray();
            if (!empty(array_intersect($validated['tags'], $tags))) {
                $game->tag()->sync(array_intersect($validated['tags'], $tags));
            }
        } else {
            $game->tag()->sync([]);
        }
        $game->save();
    }
}

resources/views/gallery/create.blade.php
@extends('layouts.master')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger mt-3" role="alert">
            <p>Des champs sont invalides</p>
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="text-center mt-3">
        <h3>Création d'un jeu</h3>
        <hr class="mt-2 mb-2">
    </div>

    <form action="{{ route('gallery.store') }}" method="POST" enctype="multipart/form-data">
        {!! csrf_field() !!}
        <div class="form-group">
            <label for="nom">Entrer le nom de votre jeu :</label>
            <input type="text" class="form-control" id="nom" name="nom" value="{{ old('nom') }}" placeholder="Pokémon">
        </div>

        <div class="form-group">
            <label for="urlimg">Image du jeu</label>
            <input type="file" class="form-control-file" id="file" name="file">
        </div>

        <div class="form-group">
            <label for="annee">Entrer l'année de sortie :</label>
            <input type="text" class="form-control" id="annee" name="annee_sortie" value="{{ old('annee_sortie') }}"
                   placeholder="2019">
        </div>
        <div class="form-group">
            <label for="age">Entrer l'age minimum pour jouer à ce jeu :</label>
            <input type="text" class="form-control" id="age" name="age_min" value="{{ old('age_min') }}"
                   placeholder="11">
        </div>
        <div class="form-group">
            <label for="min_joueur">Entrer le nombre minimum de joueur possible :</label>
            <input type="text" class="form-control" id="min_joueur" name="min_joueur" value="{{ old('min_joueur') }}"
                   placeholder="1">
        </div>
        <div class="form-group">
            <label for="max_joueur">Entrer le nombre maximum de joueur possible :</label>
            <input type="text" class="form-control" id="max_joueur" name="max_joueur" value="{{ old('max_joueur') }}"
                   placeholder="3">
        </div>
        <div class="form-group">
            <label for="min_duree">Entrer le temps de jeu minimum possible :</label>
            <input type="text" class="form-control" id="min_duree" name="min_duree" value="{{ old('min_duree') }}"
                   placeholder="12">
        </div>
        <div class="form-group">
            <label for="max_duree">Entrer le temps de jeu maximum possible :</label>
            <input type="text" class="form-control" id="max_duree" name="max_duree" value="{{ old('max_duree') }}"
                   placeholder="24">
        </div>
        <div class="form-group">
            <label for="description">Description du jeu :</label>
            <textarea name="description" id="description" cols="30" rows="10" class="form-control"
                      placeholder="C'est 2 petit bonhommes qui se battent et...">{{ old('description') }}</textarea>
        </div>

        @foreach($tags as $tag)
            <div class="form-check-inline">
                <input type="checkbox" name="tags[]" value="{{ $tag->id }}" id="{{ $tag->label }}" class="form-check-input">
                <label for="{{ $tag->label }}" class="form-check-label">{{ $tag->label }}</label>
            </div>
        @endforeach

        <div class="form-group">
            <button type="submit" class="btn btn-primary mb-3">Créer</button>
        </div>
    </form>

@endsection()

resources/views/gallery/edit.blade.php
@extends('layouts.master')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger mt-3" role="alert">
            <p>Des champs sont invalides</p>
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="text-center mt-3">
        <h3>Modification d'un jeu</h3>
        <hr class="mt-2 mb-2">
    </div>

    <form action="{{ route('gallery.update', $game->id) }}" method="POST">
        {!! csrf_field() !!}
        {!! method_field('PUT') !!}

        <div class="form-group">
            <label for="nom">Entrer le nom de votre jeu :</label>
            <input type="text" class="form-control" id="nom" name="nom" value="{{ $game->nom }}" placeholder="Pokémon">
        </div>

        <div class="form-group">
            <label for="urlimg">Url de l'image</label>
            <input type="text" class="form-control" id="urlimg" name="thumbnail" value="{{ $game->thumbnail }}" placeholder="https://picsum.photos/200/300">
        </div>

        <div class="form-group">
            <label for="annee">Entrer l'année de sortie :</label>
            <input type="text" class="form-control" id="annee" name="annee_sortie" value="{{ $game->annee_sortie }}"
                   placeholder="2019">
        </div>

        <div class="form-group">
            <label for="age">Entrer l'age minimum pour jouer à ce jeu :</label>
            <input type="text" class="form-control" id="age" name="age_min" value="{{ $game->age_min }}"
                   placeholder="11">
        </div>

        <div class="form-group">
            <label for="min_joueur">Entrer le nombre minimum de joueur possible :</label>
            <input type="text" class="form-control" id="min_joueur" name="min_joueur" value="{{ $game->min_joueur }}"
                   placeholder="1">
        </div>

        <div class="form-group">
            <label for="max_joueur">Entrer le nombre maximum de joueur possible :</label>
            <input type="text" class="form-control" id="max_joueur" name="max_joueur" value="{{ $game->max_joueur }}"
                   placeholder="3">
        </div>

        <div class="form-group">
            <label for="min_duree">Entrer le temps de jeu minimum possible :</label>
            <input type="text" class="form-control" id="min_duree" name="min_duree" value="{{ $game->min_duree }}"
                   placeholder="12">
        </div>

        <div class="form-group">
            <label for="max_duree">Entrer le temps de jeu maximum possible :</label>
            <input type="text" class="form-control" id="max_duree" name="max_duree" value="{{ $game->max_duree }}"
                   placeholder="24">
        </div>

        <div class="form-group">
            <label for="description">Description du jeu :</label>
            <textarea name="description" id="description" cols="30" rows="10" class="form-control"
                      placeholder="C'est 2 petit bonhommes qui se battent et...">{{ $game->description }}</textarea>
        </div>

        @foreach($tags as $tag)
            <div class="form-check-inline">
                @if (in_array($tag->id, $gametags))
                    <input type="checkbox" name="tags[]" value="{{ $tag->id }}" id="{{ $tag->label }}"
                           class="form-check-input" checked>
                @else
                    <input type="checkbox" name="tags[]" value="{{ $tag->id }}" id="{{ $tag->label }}"
                           class="form-check-input">
                @endif
                <label for="{{ $tag->label }}" class="form-check-label">{{ $tag->label }}</label>
            </div>
        @endforeach

        <div class="form-group">
            <button type="submit" class="btn btn-primary mb-3">Modifier</button>
        </div>
    </form>

@endsection()

resources/views/gallery/index.blade.php
@extends('layouts.master')

@section('content')

    <h1 class="text-center mt-3">Notre catalogue de jeu</h1>

    @if (Auth::check())
        <div class="text-center">
            <a href="{{ route('gallery.create') }}" class="btn btn-success ">Ajouter un jeu</a>
        </div>
    @endif

    <div class="row">
        @if(!$games->isEmpty())
            <div class="col-sm-8 mt-3">
                @foreach($games as $game)
                    <div class="card box-shadow">
                        <h3 class="card-header"><a href="{{ url('gallery', $game->id) }}">{{ $game->nom }}</a></h3>
                        <img class="card-img-top" src="{{ $game->thumbnail }}" alt="thumbnail">
                        <div class="card-body">
                            <p class="card-text">
                                {{ Str::limit($game->description, $limit = 150) }}
                            </p>
                        </div>
                    </div>
                @endforeach
            </div>
        @else
            <h2 class="text-center mt-3 text-secondary font-italic">La ludothèque est vide</h2>
    @endif

    <!-- tags widget -->
        <div class="col-sm-4 mt-3">
            <h5 class="card-header">Tags</h5>
            <ul class="list-group">
                @foreach($tags as $tag)
                    <a href="{{ route('tagged', $tag->id) }}"
                       class="list-group-item list-group-item-action">{{ $tag->label }}</a>
                @endforeach
            </ul>
        </div>
    </div>
@endsection

resources/views/gallery/show.blade.php
@extends('layouts.master')

@section('content')

    @if (Auth::check())
        <div class="text-center">
            <div class="btn-group">
                <a href="{{ route('gallery.edit', $game->id) }}" class="btn btn-primary mt-3">
                    Modifier
                </a>

                <form action="{{ route('gallery.destroy', $game->id) }}" method="post" class="mt-3">
                    {!! csrf_field() !!}
                    {!! method_field('DELETE') !!}
                    <button type="submit" class="btn btn-danger">Supprimer</button>
                </form>
            </div>
        </div>
    @endif

    <div class="row mt-3 mb-3">
        <div class="col-md-6 mx-auto">
            <div class="card mb-12 box-shadow">
                <div class="card-header">
                    <h3 class="card-title">{{ $game->nom }}</h3>
                </div>
                <img class="card-img-top" src="{{ $game->thumbnail }}" alt="thumbnail">
                <div class="card-body">
                    <p class="card-text">{{ $game->description }}</p>
                </div>
                <ul class="list-group">
                    <li class="list-group-item">
                        âge minimal : {{ $game->age_min }}
                    </li>
                    <li class="list-group-item">
                        nombres de joueur : {{ $game->min_joueur }}-{{ $game->max_joueur }} joueur
                    </li>
                    <li class="list-group-item">
                        Temps de jeu moyen : {{ $game->min_duree }}-{{ $game->max_duree }}h
                    </li>
                    <li class="list-group-item">
                        Année de sortie : {{ $game->annee_sortie }}
                    </li>
                    @if (!$tags->isEmpty())
                        <li class="list-group-item">
                            @foreach($tags as $tag)
                                <span class="badge badge-info">
                                    {{ $tag->label }}
                                </span>
                            @endforeach
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </div>

    <h1 class="text-center mt-3 mb-3">Espace commentaire</h1>

    @foreach($comments as $comment)
        <div style="border-bottom: 1px dotted #ccc;" class="mb-3">
            <div class="media-body">
                <h4>{{ $comment->user->name }}

                    @if (Auth::id() == $comment->user->id)

                        <div class="btn-group">
                            <a href="{{ route('comment.edit', $comment->id) }}" class="btn btn-primary btn-sm">
                                Modifier
                            </a>

                            <form action="{{ route('comment.destroy', $comment->id) }}" method="post">
                                {!! csrf_field() !!}
                                {!! method_field('DELETE') !!}
                                <button type="submit" class="btn btn-danger btn-sm">Supprimer</button>
                            </form>
                        </div>
                    @endif

                </h4>

                <p class="text-body">{{ $comment->body }}</p>
            </div>
        </div>
    @endforeach

    @if (Auth::check())
        <form action="{{ route('comment.store', $game->id) }}" method="POST" class="mb-3">
            {{ @csrf_field() }}
            {{ @method_field('PUT') }}
            <div class="form-group">
                <label for="body">Commentaire : </label>
                <input type="text" class="form-control" name="body" placeholder="Trop bien ce jeu !">
            </div>
            <button class="btn btn-success">Poster</button>
        </form>
    @endif
@endsection

resources/views/gallery/tagged.blade.php
@extends('layouts.master')

@section('content')

    <h1 class="text-center mt-3">Jeux ayant le tag {{ $tag->label }}</h1>

    <div class="text-center">
        <a href="{{ route('gallery.create') }}" class="btn btn-success ">Ajouter un jeu</a>
    </div>

    <div class="row">
        <div class="col-sm-8 mb-3 mt-3">
            @if(!$games->isEmpty())
                @foreach($games as $game)
                    <div class="card mb-6 box-shadow">
                        <h3 class="card-header"><a href="{{ url('gallery', $game->id) }}">{{ $game->nom }}</a></h3>
                        <img class="card-img-top" src="{{ $game->thumbnail }}" alt="thumbnail">
                        <div class="card-body">
                            <p class="card-text">
                                {{ Str::limit($game->description, $limit = 150) }}
                            </p>
                        </div>
                    </div>
                @endforeach
            @else
                <h2 class="text-center mt-3 text-secondary font-italic">La ludothèque est vide</h2>
            @endif
        </div>

        <!-- tags widget -->
        <div class="col-sm-4 mt-3">
            <h5 class="card-header">Tags</h5>
            <ul class="list-group">
                @foreach($tags as $currentTag)
                    <a href="{{ route('tagged', $currentTag->id) }}"
                       class="list-group-item list-group-item-action @if ($currentTag->id == $tag->id) active @endif">{{ $currentTag->label }}</a>
                @endforeach
            </ul>
        </div>
    </div>
@endsection